# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd954bf888d4fb96d386721c1504bef366d4893431621e79697d28c4e0395b45effbff4f1dd9fb2bf4a405eedb479aaed96306f351bd6e8591beaec16c8da02e

test:
  secret_key_base: 0d75e289fc6790bd6e230ddfe2682eed74932ba1d36d5861a460a9730fb9f29f9aec22fbf9c239f7b35eb8e7791f006876ee96b21d2ae0994588ad87ddc290c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
